export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const CHANGE_NAVBAR_ACTIVE = 'CHANGE_NAVBAR_ACTIVE'

export const SET_USER_PURCHASES = 'SET_USER_PURCHASES';
export const SET_PURCHASE_DETAIL = 'SET_PURCHASE_DETAIL';

export const SET_SHOP_CATEGORIES = 'SET_SHOP_CATEGORIES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const FILTER_PRODUCTS_WITH_QUERY = 'FILTER_PRODUCTS_WITH_QUERY';

export const ADD_USER = 'ADD_USER';
export const FETCH_USER_ADDRESS = 'FETCH_USER_ADDRESS';
export const ADDRESS_EDIT = 'ADDRESS_EDIT';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_NAME = 'EDIT_NAME';
export const EDIT_USER_NAME = 'EDIT_USER_NAME';
//USER'S CART

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS';


export const FETCH_USER_NAME = 'FETCH_USER_NAME';
export const MAKE_PURCHASE = 'MAKE_PURCHASE'